[package]
name = "cqlapi"
version = "0.1.0"
authors = ["maxim"]



[dependencies]

chrono = "*"
simpleflake = "*"


[dependencies.rustcql]

#path = "/media/sf_src/srv/deps/rustcql"
path = "../rustcql"